### ISSUE TITLE
Script misses emails without replies

### ISSUE THREAD

**Issue by agrolsy** [hijonathan/google-scripts#11] opened 2020-03-06 08:46 UTC
I noticed that the script doesn't include quite a few emails that I know there's been no response to, sent within my timeframe. It used to include that, but then I noticed that my script had been deleted from my Script account so I had to recreate it.

I've got several different email addresses in my account, and a few of them got me as bcc. Could that affect it? How can the script be changed to include that?

**Comment by hijonathan** [comment] 2020-06-10 01:52
Hi @agrolsy. I'm not sure about why the script got deleted. That's more a Google issue than anything to do with this script, but hopefully it doesn't happen again either way.

As for the multiple email addresses, that shouldn't be an issue. This script goes through any emails in the inbox it's given access to, so connecting multiple addresses to that same inbox shouldn't affect it.

As for the bcc, this script won't catch that. This script looks for emails where _you_ were last respondent on a thread. If you're bcc'd in the reply, that means you're no longer the last respondent.

I'm going to close this issue for now, but if you feel like the script isn't working as intended, just reopen it and include a screenshot of the issue to help me figure out what's going on. Thanks!

**Closed as completed by hijonathan** 2020-06-10 01:52 UTC
